CREATE TABLE STUDENT_ATT_TABLE(
	ID NUMBER PRIMARY KEY,
	COURSEID NUMBER,
	SEM_NO NUMBER,
	SUBJECTID NUMBER,
	ROLLNO VARCHAR(10),
	SUBJECT_TYPE VARCHAR(10),
	DATE_OF_ATTENDANCE VARCHAR(10),
	LECTURE_STARTTIME VARCHAR(10),
	ATT_STATUS VARCHAR(3),
	YEAR VARCHAR(10),
	USERNAME VARCHAR(15)
);

CREATE TABLE SUBJECT_TABLE(
SUBJECTID NUMBER PRIMARY KEY,
SUBJECT_NAME VARCHAR(100),
SEM_NO NUMBER,
COURSEID NUMBER,
LECT_PER_WEEK NUMBER,
PRAC_PER_WEEK NUMBER,
TUT_PER_WEEK NUMBER,
COURSETYPE VARCHAR(10)
);
